# Learned Hearts AI weights
from hearts_ai import AIWeights
from hearts_game import GameMode

LEARNED_WEIGHTS = {
    GameMode.PLAYER_4:     AIWeights(
        pass_queen_of_spades=99.75,
        queen_protection_threshold=3,
        pass_to_void_suit=80.20,
        void_minor_suit_bonus=5.04,
        pass_high_hearts=69.83,
        high_heart_threshold=10,
        pass_high_cards=49.85,
        high_card_threshold=12,
        pass_base_priority=0.05,
        lead_clubs_priority=39.90,
        lead_diamonds_priority=29.91,
        lead_spades_priority=19.91,
        lead_hearts_priority=10.07,
        lead_low_card_preference=2.01,
        discard_queen_of_spades=99.78,
        discard_hearts=79.80,
        discard_dangerous_spades=60.17,
        discard_high_cards=39.87,
        discard_rank_multiplier=1.00,
        high_duck_preference=1.00,
        low_win_preference=1.00,
        take_safe_trick_preference=1.00,
        moon_threat_threshold=10,
        moon_block_priority=50.15,
    ),
    GameMode.PLAYER_3_REMOVE:     AIWeights(
        pass_queen_of_spades=100.80,
        queen_protection_threshold=3,
        pass_to_void_suit=79.33,
        void_minor_suit_bonus=4.96,
        pass_high_hearts=69.44,
        high_heart_threshold=10,
        pass_high_cards=49.70,
        high_card_threshold=12,
        pass_base_priority=-0.11,
        lead_clubs_priority=39.94,
        lead_diamonds_priority=30.09,
        lead_spades_priority=19.86,
        lead_hearts_priority=10.19,
        lead_low_card_preference=1.97,
        discard_queen_of_spades=100.07,
        discard_hearts=79.25,
        discard_dangerous_spades=59.38,
        discard_high_cards=40.14,
        discard_rank_multiplier=0.99,
        high_duck_preference=1.00,
        low_win_preference=0.99,
        take_safe_trick_preference=1.01,
        moon_threat_threshold=10,
        moon_block_priority=50.60,
    ),
    GameMode.PLAYER_3_KITTY:     AIWeights(
        pass_queen_of_spades=99.33,
        queen_protection_threshold=3,
        pass_to_void_suit=79.63,
        void_minor_suit_bonus=5.16,
        pass_high_hearts=70.53,
        high_heart_threshold=10,
        pass_high_cards=50.43,
        high_card_threshold=12,
        pass_base_priority=0.12,
        lead_clubs_priority=40.15,
        lead_diamonds_priority=29.96,
        lead_spades_priority=19.98,
        lead_hearts_priority=9.99,
        lead_low_card_preference=1.97,
        discard_queen_of_spades=99.34,
        discard_hearts=78.98,
        discard_dangerous_spades=59.69,
        discard_high_cards=39.80,
        discard_rank_multiplier=1.00,
        high_duck_preference=0.99,
        low_win_preference=1.00,
        take_safe_trick_preference=0.98,
        moon_threat_threshold=10,
        moon_block_priority=49.45,
    ),
}
