# Learned Hearts AI weights
from hearts_ai import AIWeights
from hearts_game import GameMode

LEARNED_WEIGHTS = {
    GameMode.PLAYER_4:     AIWeights(
        pass_queen_of_spades=112.48,
        queen_protection_threshold=3,
        pass_to_void_suit=89.98,
        void_minor_suit_bonus=11.19,
        pass_high_hearts=74.57,
        high_heart_threshold=10,
        pass_high_cards=57.21,
        high_card_threshold=12,
        pass_base_priority=2.50,
        lead_clubs_priority=44.99,
        lead_diamonds_priority=36.11,
        lead_spades_priority=26.28,
        lead_hearts_priority=17.55,
        lead_low_card_preference=3.11,
        discard_queen_of_spades=114.62,
        discard_hearts=89.61,
        discard_dangerous_spades=72.55,
        discard_high_cards=55.10,
        discard_rank_multiplier=1.87,
        high_duck_preference=1.37,
        low_win_preference=1.37,
        take_safe_trick_preference=1.37,
        moon_threat_threshold=11,
        moon_block_priority=57.21,
    ),
    GameMode.PLAYER_3_REMOVE:     AIWeights(
        pass_queen_of_spades=112.48,
        queen_protection_threshold=3,
        pass_to_void_suit=89.98,
        void_minor_suit_bonus=11.29,
        pass_high_hearts=74.90,
        high_heart_threshold=10,
        pass_high_cards=57.21,
        high_card_threshold=12,
        pass_base_priority=2.40,
        lead_clubs_priority=44.99,
        lead_diamonds_priority=36.28,
        lead_spades_priority=26.28,
        lead_hearts_priority=17.55,
        lead_low_card_preference=3.13,
        discard_queen_of_spades=115.05,
        discard_hearts=89.61,
        discard_dangerous_spades=72.22,
        discard_high_cards=55.10,
        discard_rank_multiplier=1.88,
        high_duck_preference=1.38,
        low_win_preference=1.37,
        take_safe_trick_preference=1.38,
        moon_threat_threshold=11,
        moon_block_priority=57.21,
    ),
    GameMode.PLAYER_3_KITTY:     AIWeights(
        pass_queen_of_spades=112.01,
        queen_protection_threshold=3,
        pass_to_void_suit=89.61,
        void_minor_suit_bonus=11.19,
        pass_high_hearts=74.57,
        high_heart_threshold=10,
        pass_high_cards=57.21,
        high_card_threshold=12,
        pass_base_priority=2.50,
        lead_clubs_priority=44.80,
        lead_diamonds_priority=36.11,
        lead_spades_priority=26.11,
        lead_hearts_priority=17.40,
        lead_low_card_preference=3.13,
        discard_queen_of_spades=114.62,
        discard_hearts=89.61,
        discard_dangerous_spades=72.22,
        discard_high_cards=54.81,
        discard_rank_multiplier=1.87,
        high_duck_preference=1.37,
        low_win_preference=1.38,
        take_safe_trick_preference=1.37,
        moon_threat_threshold=11,
        moon_block_priority=57.21,
    ),
}
